#!/usr/bin/env python3
"""Crawl Japanese ads from Meta Ad Library API.

Reads keywords from exports/crawl_keywords.json (generated by
generate_crawl_keywords.py) and fetches matching ads via the Meta Ad
Library API (v18.0).  New ads are deduplicated by external_id and
inserted into the local SQLite/PostgreSQL database with auto-assigned
category based on the crawl keyword.

If META_ACCESS_TOKEN is not set, performs a DRY RUN that prints what
would be crawled without making actual API calls.

Usage:
    cd C:/Users/ishit/ads_library/backend
    python scripts/crawl_japanese_ads.py
"""

import io
import json
import os
import sys
import time
from datetime import datetime, timezone

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import requests as http_requests
from sqlalchemy import select

from app.core.database import SyncSessionLocal
from app.models.ad import Ad, AdCategoryEnum, AdPlatformEnum, AdStatusEnum


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXPORTS_DIR = os.path.join(BACKEND_DIR, "exports")

# Primary: output from generate_crawl_keywords.py
KEYWORDS_PATH = os.path.join(EXPORTS_DIR, "crawl_keywords.json")
# Fallback: suggestion file that generate_crawl_keywords.py writes
KEYWORDS_SUGGESTION_PATH = os.path.join(EXPORTS_DIR, "crawl_keywords_suggestion.json")
# Secondary fallback: static config
KEYWORDS_CONFIG_PATH = os.path.join(BACKEND_DIR, "config", "crawl_keywords.json")


# ---------------------------------------------------------------------------
# Meta Ad Library API settings
# ---------------------------------------------------------------------------

META_API_BASE = "https://graph.facebook.com/v18.0/ads_archive"
META_API_FIELDS = ",".join([
    "id",
    "ad_creative_bodies",
    "ad_creative_link_titles",
    "page_name",
    "ad_delivery_start_time",
    "ad_snapshot_url",
    "publisher_platforms",
])
REQUEST_DELAY_SECONDS = 2  # polite delay between API calls


# ---------------------------------------------------------------------------
# Keyword -> category mapping
# ---------------------------------------------------------------------------

KEYWORD_CATEGORY_MAP: dict[str, AdCategoryEnum] = {
    # Beauty / cosmetics
    "beauty": AdCategoryEnum.BEAUTY,
    "skincare": AdCategoryEnum.BEAUTY,
    "cosmetics": AdCategoryEnum.BEAUTY,
    "whitening": AdCategoryEnum.BEAUTY,
    "esthetics": AdCategoryEnum.BEAUTY,
    "hair_removal": AdCategoryEnum.BEAUTY,
    "beauty_clinic": AdCategoryEnum.BEAUTY,
    # Health
    "diet": AdCategoryEnum.HEALTH,
    "diet_supplement": AdCategoryEnum.HEALTH,
    "supplement": AdCategoryEnum.HEALTH,
    "protein": AdCategoryEnum.HEALTH,
    "protein_supplement": AdCategoryEnum.HEALTH,
    "health_food": AdCategoryEnum.HEALTH,
    "hair_growth": AdCategoryEnum.HEALTH,
    "hair_growth_aga": AdCategoryEnum.HEALTH,
    "medical_weight_loss": AdCategoryEnum.HEALTH,
    "fat_burning": AdCategoryEnum.HEALTH,
    # Fitness
    "fitness": AdCategoryEnum.HEALTH,
    "yoga": AdCategoryEnum.HEALTH,
    "yoga_pilates": AdCategoryEnum.HEALTH,
    "muscle_training": AdCategoryEnum.HEALTH,
    # Finance
    "finance": AdCategoryEnum.FINANCE,
    "finance_investment": AdCategoryEnum.FINANCE,
    # Education
    "education": AdCategoryEnum.EDUCATION,
    "education_school": AdCategoryEnum.EDUCATION,
    # EC / Shopping
    "ec_shopping": AdCategoryEnum.EC_D2C,
    # App
    "app": AdCategoryEnum.APP,
    # Real estate
    "real_estate": AdCategoryEnum.REAL_ESTATE,
    # Jobs (no exact enum; map to OTHER)
    "jobs_recruitment": AdCategoryEnum.OTHER,
}

# Japanese keyword text -> genre slug (best effort)
JP_KEYWORD_TO_GENRE: dict[str, str] = {}


def _guess_category_from_keyword(keyword: str, genre: str | None = None) -> AdCategoryEnum:
    """Map a crawl keyword/genre to an AdCategoryEnum value."""
    # Try genre slug first
    if genre:
        slug = genre.lower().replace(" ", "_")
        if slug in KEYWORD_CATEGORY_MAP:
            return KEYWORD_CATEGORY_MAP[slug]

    # Try exact keyword match against known slugs
    kw_lower = keyword.lower().replace(" ", "_")
    for slug, cat in KEYWORD_CATEGORY_MAP.items():
        if slug in kw_lower:
            return cat

    return AdCategoryEnum.OTHER


# ---------------------------------------------------------------------------
# Load keywords
# ---------------------------------------------------------------------------

def load_keywords() -> list[dict]:
    """Load crawl keywords from the exports/crawl_keywords.json file.

    Expected format (from generate_crawl_keywords.py):
      {
        "keyword_suggestions": [
          { "genre": "skincare", "label": "Skincare", "keywords": [...], "priority": "high" },
          ...
        ]
      }

    Fallback: config/crawl_keywords.json (flat keyword list).

    Returns a list of dicts, each with keys: genre, label, keywords, priority.
    """
    # Try primary path
    for path in [KEYWORDS_PATH, KEYWORDS_SUGGESTION_PATH]:
        if os.path.exists(path):
            try:
                with open(path, "r", encoding="utf-8") as f:
                    data = json.load(f)

                suggestions = data.get("keyword_suggestions")
                if suggestions and isinstance(suggestions, list):
                    print(f"Loaded keyword suggestions from {path}")
                    print(f"  Genres: {len(suggestions)}")
                    return suggestions
            except Exception as e:
                print(f"WARNING: Failed to parse {path}: {e}")

    # Fallback: config/crawl_keywords.json (flat list)
    if os.path.exists(KEYWORDS_CONFIG_PATH):
        try:
            with open(KEYWORDS_CONFIG_PATH, "r", encoding="utf-8") as f:
                data = json.load(f)

            flat_keywords = data.get("keywords", [])
            if flat_keywords:
                print(f"Loaded flat keywords from {KEYWORDS_CONFIG_PATH}")
                print(f"  Keywords: {len(flat_keywords)}")
                # Wrap into a single genre group
                return [{
                    "genre": "general",
                    "label": "General",
                    "keywords": flat_keywords,
                    "priority": "medium",
                }]
        except Exception as e:
            print(f"WARNING: Failed to parse {KEYWORDS_CONFIG_PATH}: {e}")

    print("ERROR: No crawl keywords file found.")
    print(f"  Checked: {KEYWORDS_PATH}")
    print(f"  Checked: {KEYWORDS_SUGGESTION_PATH}")
    print(f"  Checked: {KEYWORDS_CONFIG_PATH}")
    print("  Run generate_crawl_keywords.py first to create the keywords file.")
    return []


# ---------------------------------------------------------------------------
# Meta Ad Library API
# ---------------------------------------------------------------------------

def fetch_ads_from_meta(access_token: str, keyword: str, limit: int = 50) -> list[dict]:
    """Fetch ads from Meta Ad Library API for a single keyword.

    Returns a list of raw ad dicts from the API response.
    """
    params = {
        "access_token": access_token,
        "search_terms": keyword,
        "ad_reached_countries": "JP",
        "ad_type": "ALL",
        "fields": META_API_FIELDS,
        "limit": min(limit, 100),  # API max per page
    }

    all_ads: list[dict] = []
    url = META_API_BASE

    while url and len(all_ads) < limit:
        try:
            resp = http_requests.get(url, params=params, timeout=30)
            resp.raise_for_status()
            data = resp.json()
        except http_requests.exceptions.HTTPError as e:
            status = e.response.status_code if e.response is not None else "?"
            print(f"API error (HTTP {status}): {e}")
            break
        except http_requests.exceptions.RequestException as e:
            print(f"Request error: {e}")
            break
        except ValueError:
            print("ERROR: Invalid JSON response from Meta API")
            break

        ads_page = data.get("data", [])
        all_ads.extend(ads_page)

        # Pagination
        paging = data.get("paging", {})
        next_url = paging.get("next")
        if next_url and len(all_ads) < limit:
            url = next_url
            params = {}  # next URL contains all params
            time.sleep(REQUEST_DELAY_SECONDS)
        else:
            break

    return all_ads[:limit]


def parse_meta_ad(raw_ad: dict, keyword: str, genre: str, today_str: str) -> dict:
    """Parse a raw Meta API ad response into a dict suitable for Ad model."""
    ad_id = raw_ad.get("id", "")
    external_id = f"meta_{ad_id}" if ad_id else None

    # Extract text fields
    bodies = raw_ad.get("ad_creative_bodies", [])
    description = bodies[0] if bodies else None

    titles = raw_ad.get("ad_creative_link_titles", [])
    title = titles[0] if titles else None

    page_name = raw_ad.get("page_name")
    snapshot_url = raw_ad.get("ad_snapshot_url")

    # Delivery start time -> first_seen_at
    delivery_start = raw_ad.get("ad_delivery_start_time")
    first_seen_at = None
    if delivery_start:
        try:
            first_seen_at = datetime.fromisoformat(
                delivery_start.replace("Z", "+00:00")
            )
        except (ValueError, AttributeError):
            pass

    # Publisher platforms -> determine platform enum
    publisher_platforms = raw_ad.get("publisher_platforms", [])
    if "instagram" in publisher_platforms:
        platform = AdPlatformEnum.INSTAGRAM
    elif "facebook" in publisher_platforms:
        platform = AdPlatformEnum.FACEBOOK
    else:
        platform = AdPlatformEnum.FACEBOOK  # default for Meta API

    return {
        "external_id": external_id,
        "title": title,
        "description": description,
        "platform": platform,
        "advertiser_name": page_name,
        "snapshot_url": snapshot_url,
        "first_seen_at": first_seen_at,
        "last_seen_at": datetime.now(timezone.utc),
        "ad_metadata": {
            "source": "api_crawl",
            "crawl_keyword": keyword,
            "crawl_date": today_str,
            "fine_genre_en": genre,
            "publisher_platforms": publisher_platforms,
            "meta_ad_id": ad_id,
        },
    }


# ---------------------------------------------------------------------------
# Database operations
# ---------------------------------------------------------------------------

def get_existing_external_ids(session, external_ids: list[str]) -> set[str]:
    """Fetch external_ids that already exist in the database."""
    if not external_ids:
        return set()

    # Query in batches to avoid overly large IN clauses
    existing = set()
    batch_size = 500
    for i in range(0, len(external_ids), batch_size):
        batch = external_ids[i : i + batch_size]
        stmt = select(Ad.external_id).where(Ad.external_id.in_(batch))
        rows = session.execute(stmt).scalars().all()
        existing.update(r for r in rows if r is not None)

    return existing


def insert_ads(session, parsed_ads: list[dict], category: AdCategoryEnum) -> tuple[int, int]:
    """Insert parsed ads into the database, skipping duplicates.

    Returns (new_count, duplicate_count).
    """
    if not parsed_ads:
        return 0, 0

    # Pre-fetch existing external_ids for deduplication
    candidate_ids = [a["external_id"] for a in parsed_ads if a.get("external_id")]
    existing_ids = get_existing_external_ids(session, candidate_ids)

    new_count = 0
    dup_count = 0

    for ad_data in parsed_ads:
        ext_id = ad_data.get("external_id")

        # Skip duplicates
        if ext_id and ext_id in existing_ids:
            dup_count += 1
            continue

        ad = Ad(
            external_id=ext_id,
            title=ad_data.get("title"),
            description=ad_data.get("description"),
            platform=ad_data.get("platform", AdPlatformEnum.FACEBOOK),
            status=AdStatusEnum.PENDING,
            category=category,
            creative_type="unknown",
            advertiser_name=ad_data.get("advertiser_name"),
            snapshot_url=ad_data.get("snapshot_url"),
            first_seen_at=ad_data.get("first_seen_at"),
            last_seen_at=ad_data.get("last_seen_at"),
            ad_metadata=ad_data.get("ad_metadata", {}),
        )
        session.add(ad)
        new_count += 1

        # Track inserted id to avoid intra-batch duplicates
        if ext_id:
            existing_ids.add(ext_id)

    session.commit()
    return new_count, dup_count


# ---------------------------------------------------------------------------
# Dry run mode
# ---------------------------------------------------------------------------

ESTIMATED_ADS_PER_KEYWORD = 25  # rough estimate for dry-run output


def dry_run(keyword_groups: list[dict]):
    """Print what would be crawled without making API calls."""
    print()
    print("=" * 64)
    print("  DRY RUN MODE (META_ACCESS_TOKEN not set)")
    print("=" * 64)
    print()
    print("  Set the META_ACCESS_TOKEN environment variable to enable")
    print("  actual API calls to the Meta Ad Library.")
    print()

    total_keywords = 0
    total_estimated_ads = 0
    genres_covered = set()

    print(f"  {'Genre':<30s} {'Keywords':>8s} {'Est. Ads':>10s}  Priority")
    print(f"  {'-' * 65}")

    for group in keyword_groups:
        genre = group.get("genre", "unknown")
        label = group.get("label", genre)
        keywords = group.get("keywords", [])
        priority = group.get("priority", "medium")
        kw_count = len(keywords)
        est_ads = kw_count * ESTIMATED_ADS_PER_KEYWORD

        genres_covered.add(genre)
        total_keywords += kw_count
        total_estimated_ads += est_ads

        print(f"  {label:<30s} {kw_count:>8d} {est_ads:>10d}  [{priority}]")

    print()
    print(f"  Total genres:            {len(genres_covered)}")
    print(f"  Total keywords:          {total_keywords}")
    print(f"  Estimated ads (total):   {total_estimated_ads}")
    print()

    # Print sample keywords per genre
    print("  Sample keywords per genre:")
    print(f"  {'-' * 55}")
    for group in keyword_groups:
        genre = group.get("genre", "unknown")
        keywords = group.get("keywords", [])
        if not keywords:
            continue
        print(f"  [{genre}]")
        for kw in keywords[:3]:
            kw_safe = kw.encode("ascii", "replace").decode("ascii")
            print(f"    - {kw_safe}")
        if len(keywords) > 3:
            print(f"    ... and {len(keywords) - 3} more")
        print()

    print(f"Crawled 0 new ads, 0 duplicates skipped, {len(genres_covered)} genres covered")
    print("(Dry run -- no API calls made)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 64)
    print("  Meta Ad Library API Crawler - Japanese Ads")
    print(f"  Executed at: {datetime.now(timezone.utc).isoformat()}")
    print("=" * 64)

    # Load keywords
    keyword_groups = load_keywords()
    if not keyword_groups:
        return

    # Check for access token
    access_token = os.environ.get("META_ACCESS_TOKEN", "").strip()
    if not access_token:
        print()
        print("WARNING: META_ACCESS_TOKEN environment variable is not set.")
        print("Running in DRY RUN mode.")
        dry_run(keyword_groups)
        return

    # Live crawl mode
    today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    total_new = 0
    total_duplicates = 0
    genres_covered = set()

    print(f"\nAccess token: ...{access_token[-8:]}")
    print(f"API endpoint: {META_API_BASE}")
    print(f"Target country: JP")
    print(f"Keyword groups: {len(keyword_groups)}")
    print()

    for gi, group in enumerate(keyword_groups):
        genre = group.get("genre", "unknown")
        label = group.get("label", genre)
        keywords = group.get("keywords", [])
        priority = group.get("priority", "medium")

        if not keywords:
            print(f"[{gi + 1}/{len(keyword_groups)}] {label} -- no keywords, skipping")
            continue

        genres_covered.add(genre)
        category = _guess_category_from_keyword("", genre)

        print(f"[{gi + 1}/{len(keyword_groups)}] Genre: {label} ({len(keywords)} keywords, priority={priority})")
        print("-" * 50)

        genre_new = 0
        genre_dup = 0

        for ki, keyword in enumerate(keywords):
            kw_safe = keyword.encode("ascii", "replace").decode("ascii")
            print(f"  [{ki + 1}/{len(keywords)}] Keyword: {kw_safe} ...", end=" ", flush=True)

            try:
                raw_ads = fetch_ads_from_meta(access_token, keyword, limit=50)
                print(f"fetched {len(raw_ads)}", end=" ", flush=True)
            except Exception as e:
                print(f"ERROR: {str(e)[:60]}")
                continue

            if not raw_ads:
                print("-> 0 results")
                continue

            # Parse ads
            parsed = []
            for raw in raw_ads:
                parsed_ad = parse_meta_ad(raw, keyword, genre, today_str)
                if parsed_ad.get("external_id"):
                    parsed.append(parsed_ad)

            # Insert into DB
            session = SyncSessionLocal()
            try:
                new_count, dup_count = insert_ads(session, parsed, category)
                genre_new += new_count
                genre_dup += dup_count
                print(f"-> {new_count} new, {dup_count} duplicates")
            except Exception as db_err:
                session.rollback()
                print(f"DB error: {db_err}")
            finally:
                session.close()

            # Polite delay between API calls
            if ki < len(keywords) - 1:
                time.sleep(REQUEST_DELAY_SECONDS)

        total_new += genre_new
        total_duplicates += genre_dup
        print(f"  Genre subtotal: {genre_new} new, {genre_dup} duplicates")
        print()

    # Final summary
    print("=" * 64)
    print("  CRAWL COMPLETE")
    print("=" * 64)
    print()
    print(f"Crawled {total_new} new ads, {total_duplicates} duplicates skipped, {len(genres_covered)} genres covered")
    print()

    # DB stats
    session = SyncSessionLocal()
    try:
        total_ads = session.query(Ad).count()
        api_crawl_count = 0
        all_ads = session.query(Ad).all()
        for ad in all_ads:
            if (ad.ad_metadata or {}).get("source") == "api_crawl":
                api_crawl_count += 1
        print(f"  DB total ads:       {total_ads}")
        print(f"  API-crawled ads:    {api_crawl_count}")
    except Exception as e:
        print(f"  DB stats error: {e}")
    finally:
        session.close()


if __name__ == "__main__":
    main()
